# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

#bind = Super, B, global, quickshell:sidebarLeftToggle # [hidden]
bindd = Super, B, Toggle bar, global, quickshell:barToggle # Toggle bar
bind = SUPER, J, layoutmsg, togglesplit #Toggle Split
# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above


#Copy from the repo to the working quickshell for faster iterations
bind = CTRL+SHIFT+SUPER, R, exec, /home/syny/Dev/dots-hyprland/setup quickshell#Quickshell repo to working

#Copy from the repo to the working hyprland folder
bind = CTRL+SHIFT+SUPER, H, exec, cp -r /home/syny/Dev/dots-hyprland/dots/.config/hypr/. /home/syny/.config/hypr #Hypr repo to working
