# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

#exec = notify-send "Hyprland rules.conf loaded!"

# Put Unity on workspace 1, Rider on workspace 2
windowrule = workspace 1 silent, match:class ^(Unity)$
#windowrule = workspace 3 silent, match:class ^(jetbrains-rider)$
# All Chromium/Chrome variants on workspace 6
#windowrule = workspace 6 silent, match:class ^(Chromium|Google-chrome|chromium|chrome)$
#windowrule = workspace 5, match:class ^(unityhub)$
#windowrule = workspace 5, match:class ^(plasticx)$
#windowrule = workspace 3, match:class ^(jetbrains-rider)$
#windowrule = float 0, match:class ^(jetbrains-rider)$

decoration {
    # .
    blur {
        enabled = true
        size = 4
        passes = 1
        noise = 0.00
        contrast = 0.8
        brightness = 1.0
    }
}
windowrule = match:class ^(kitty)$, opacity 0.8 
windowrule = match:class ^(kitty)$, no_blur off 
windowrule = match:class ^(org.kde.dolphin)$, opacity 0.8
windowrule = match:class ^(org.kde.dolphin)$, no_blur off

windowrule = match:class ^(kitty)$, match:title .*(nvim).*, opacity 1 override
# decoration {
#     screen_shader = ~/.config/hypr/custom/shaders/wobble.frag
# }
#plugin:darkwindow {
#  shader[test] {
#    path = /home/syny/.config/hypr/custom/shaders/test.glsl 
#    #args = tintColor=[1.0 0.5 0.0] tintStrength=0.2  # Orange tint
#    introduces_transparency = false
#  }
#
#  shader[tintRed] {
#      from = tint
#      args = tintColor=[1 0 0] tintStrength=0.1
#  }
#}
#windowrule = darkwindow:shade tint, match:class (kitty)
#windowrule = darkwindow:shade invert, match:class (kitty)
